In [2]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [7]:
# Your code here
A = np.random.randint(1,10,(3,3))
B = np.random.randint(1,10,(3,3))
print(A)
print(B)

[[2 5 1]
 [6 9 1]
 [3 7 4]]
[[9 3 5]
 [3 7 5]
 [9 7 2]]


# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [8]:
# Your code here
print(A+B)
print(A*B)
print(np.dot(A,B))

[[11  8  6]
 [ 9 16  6]
 [12 14  6]]
[[18 15  5]
 [18 63  5]
 [27 49  8]]
[[42 48 37]
 [90 88 77]
 [84 86 58]]


# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [12]:
# Your code here
def sum_array(arr):
    result = np.sum(arr)
    return result
arr = np.array([[1,2,3,4],[5,6,7,8]])
sum_array(arr)

36